### PR TITLE
Update forge Version closed

### PR DESCRIPTION
**Pull request by LOLDERP**
Update to the latest version of forge

sorry i didn't do a lot

closed

### CODE REVIEW

**Comment by LOLDERP** [comment]
what build failed it worked for me

**Comment by simon816** [comment]
Not worth a Pull Request.
Remember the contributing guidelines https://docs.spongepowered.org/en/contributing/guidelines.html

>Please don’t submit pull request for small changes under 20 lines. Instead, join #spongedev on IRC (irc.esper.net) and we’ll change it together with the other smaller changes.

**Comment by LOLDERP** [comment]
oh nooooooooo

**Comment by gabizou** [comment]
I'd recommend changing the email associated with git committing as Spongy will never make a commit on her own.

**Comment by LOLDERP** [comment]
hey gabizou

**Comment by LOLDERP** [comment]
testing 123

**Pull request closed without merging**
