### PR TITLE
Key bindings implementation

### PR DESCRIPTION
**Pull request by Cybermaxke**
[API](https://github.com/SpongePowered/SpongeAPI/pull/1210) | [Common](https://github.com/SpongePowered/SpongeCommon/pull/682) | Forge | [LiteMod](https://github.com/Cybermaxke/LiteSpongeClient/releases/)

### CODE REVIEW

**Comment by bloodmc** [comment]
@ZephireNZ please update this PR and make sure it compiles.

**Comment by bloodmc** [comment]
@Cybermaxke  please update this PR and make sure it compiles.

**Comment by ZephireNZ** [comment]
Don't pretend I didn't see that ;P

**Comment by ImMorpheus** [comment]
Closing this given the age that has passed and the lack of activity. If someone wants to continue the work done here then we can re-open at a later time.

**Pull request closed without merging**
