### PR TITLE
Make use of GitHub templates

### PR DESCRIPTION
**Pull request by Grinch**
**SpongeAPI Pull Request**: n/a
**SpongeCommon Pull Request**: n/a

**Changes made within this pull request**
  - [x] Added a template for pull requests
  - [x] Moved contributing template to .github folder

### CODE REVIEW

**Comment by phroa** [comment]
(this applies to all of them)

I think the template should start out the PR as a WIP, and include check boxes in the change list.

**Comment by Minecrell** [comment]
Also this should preferably use more Markdown magic so everything looks shiny :)

**Comment by phroa** [comment]
should the sibling PRs be templated like `[SpongeAPI Pull Request](your pr here) | [SpongeCommon Pull Request](your pr here) | [SpongeForge Pull Request](your pr here) | [SpongeVanilla Pull Request](your pr here)` to set up the links or is that too unwieldy/unclear?

**Comment by Grinch** [comment]
@phroa I can do the checkboxes (already done) but I cannot change the title of a PR by default with the templates unless I missed something.

**Comment by gabizou** [comment]
Personally, I prefer having the traditional link to all related PR's much like how some of the current PR's have been formatted where the related PR's are liked as such:

**SpongeAPI** | [SpongeCommon]() | [SpongeForge]() |  [SpongeVanilla]()

Thoughts are welcome.

**Comment by Grinch** [comment]
@gabizou My only issue with that is that requires the common sense from people to remove those parts as needed and add the links in the right spot. I know you and myself are capable of understanding markdown but I worry for the rest of the planet.

Remember, this is a template. Not an automatic process. People are still required to manually manipulate the markdown when you start getting too advanced with it.

**Comment by ST-DDT** [comment]
@Grinch If we provide a template, then we automatically have some base structure and raw content, that allows/Forces new users to learn markdown. Remember they have the preview option to see the result.
Users are still able to remove the template content entirely if the don't get it.

Different question:
Why do you move the contribution guidelines? AFAIC other git GUIs such as GitLab make use of it as well.

**Comment by Grinch** [comment]
@ST-DDT I'm simply trying to make it straight-forward.

I moved it because they support it there. Figured I'd put all the templates in one spot. As with all features, 3rd party programs will update to support new features.

**Comment by Aaron1011** [comment]
Can you add an issue template? It should have spaces for the Sponge and Forge versions.

**Comment by Grinch** [comment]
I plan to change it again based on suggestions made. Will add an issue template with that change.

**Comment by Grinch** [comment]
Closing for now until I finish.

**Pull request closed without merging**
